<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
    "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta charset="utf-8">
<title>Issue 1369: rethrow_exception may introduce data races</title>
<style type="text/css">
  p {text-align:justify}
  li {text-align:justify}
  blockquote.note
  {
    background-color:#E0E0E0;
    padding-left: 15px;
    padding-right: 15px;
    padding-top: 1px;
    padding-bottom: 1px;
  }
  ins {background-color:#A0FFA0}
  del {background-color:#FFA0A0}
  table {border-collapse: collapse;}
</style>
</head>
<body>
<hr>
<h3><a name="1369" href="1369">1369.</a> <tt>rethrow_exception</tt> may introduce data races</h3>
<p><b>Section:</b> 21.8.6 <a href="https://timsong-cpp.github.io/cppwp/propagation">[propagation]</a> <b>Status:</b> <a href="lwg-active.html#NAD">NAD</a>
 <b>Submitter:</b> BSI <b>Opened:</b> 2010-08-25 <b>Last modified:</b> 2016-01-28 10:01:27 UTC</p>
<p><b>Priority: </b>Not Prioritized
</p>
<p><b>View all other</b> <a href="lwg-index.html#propagation">issues</a> in <a href="https://timsong-cpp.github.io/cppwp/propagation">[propagation]</a>.</p>
<p><b>View all issues with</b> <a href="lwg-status.html#NAD">NAD</a> status.</p>
<p><b>Discussion:</b></p>
<p><b>Addresses GB-74</b></p>
<p>
One idea for the <tt>exception_ptr</tt> type was that a reference-counted
implementation could simply 'reactivate' the same
exception object in the context of a call to
<tt>rethrow_exception</tt>. Such an implementation would allow
the same exception object to be active in multiple threads
(such as when multiple threads join on a <tt>shared_future</tt>)
and introduce potential data races in any exception
handler that catches exceptions by reference - notably
existing library code written before this capability was
added. <tt>rethrow_exception</tt> should <em>always</em> make a copy
of the target exception object.
</p>

<p><i>[Resolution suggested by NB comment]</i></p>


<p>
Add the following to 18.8.5, [propogation]
</p>
<blockquote><p><ins>
<i>Throws</i>: a copy of the exception object to which <tt>p</tt> refers.
</ins></p></blockquote>

<p><i>[2011-03-15: Anthony drafts wording]</i></p>


<p><i>[2011-03-23 Madrid meeting]</i></p>


<p>No consensus for a change</p>



<p><b>Rationale:</b></p><p>It would break too many existing implementations</p>

<p><b>Proposed resolution:</b></p>

<ol>
<li><p>Alter 18.1 <a href="https://timsong-cpp.github.io/cppwp/except.throw">[except.throw]</a> p. 5 as follows:</p>

<blockquote><p>
5 When the thrown object is a class object, the copy/move constructor and the destructor shall be accessible,
even if the copy/move operation is elided (15.8 <a href="https://timsong-cpp.github.io/cppwp/class.copy">[class.copy]</a>). <ins>The copy constructor shall be
accessible, and is odr-used (6.2 <a href="https://timsong-cpp.github.io/cppwp/basic.def.odr">[basic.def.odr]</a>), even if the copy operation is elided, 
or a move constructor used to construct the exception object.</ins>
</p></blockquote>
</li>

<li><p>Alter 21.8.6 <a href="https://timsong-cpp.github.io/cppwp/propagation">[propagation]</a> p. 7 as follows:</p>

<blockquote><pre>
exception_ptr current_exception() noexcept;
</pre><blockquote>
<p>
7 <i>Returns</i>: An <tt>exception_ptr</tt> object that refers to <del>the currently handled exception 
(18.3 <a href="https://timsong-cpp.github.io/cppwp/except.handle">[except.handle]</a>) or</del> a copy of the currently handled exception, or a null <tt>exception_ptr</tt> 
object if no exception is being handled. The referenced object shall remain valid at least as long as there 
is an <tt>exception_ptr</tt> object that refers to it. If the function needs to allocate memory and the 
attempt fails, it returns an <tt>exception_ptr</tt> object that refers to an instance of <tt>bad_alloc</tt>. 
It is unspecified whether the return values of two successive calls to <tt>current_exception</tt> refer to 
the same exception object. [ <i>Note</i>: That is, it is unspecified whether <tt>current_exception</tt> 
creates a new copy each time it is called. &mdash; <i>end note</i> ] If the attempt to copy the current 
exception object throws an exception,<ins> or is otherwise not possible,</ins> the function returns an 
<tt>exception_ptr</tt> object that refers to the thrown exception <ins>if any</ins> or, <del>if this is not possible,</del> 
to an instance of <tt>bad_exception</tt>. [ <i>Note</i>: The copy constructor of the thrown exception 
may also fail, so the implementation is allowed to substitute a <tt>bad_exception</tt> object to avoid 
infinite recursion. &mdash; <i>end note</i> ]
</p>
</blockquote></blockquote>
</li>

<li><p>Alter 21.8.6 <a href="https://timsong-cpp.github.io/cppwp/propagation">[propagation]</a> p. 9 and add a new paragraph after p. 9 as follows:</p>

<blockquote><pre>
[[noreturn]] void rethrow_exception(exception_ptr p);
</pre><blockquote>
<p>
8 <i>Requires</i>: <tt>p</tt> shall not be a null pointer.
<p/>
9 <i>Throws</i>: <ins>a copy of</ins> the exception object to which <tt>p</tt> refers<ins>, or any exception 
thrown by the attempt to copy the exception object to which <tt>p</tt> refers</ins>.
<p/>
<ins>? <i>Synchronization</i>: Calls to <tt>rethrow_exception</tt> on <tt>exception_ptr</tt> objects
that refer to the same exception object shall appear to occur in a single total order. The completion 
of each call shall synchronize with (4.7 <a href="https://timsong-cpp.github.io/cppwp/intro.multithread">[intro.multithread]</a>) the next call in that total order.</ins>
</p>
</blockquote></blockquote>
</li>
</ol>






</body>
</html>
